# Generated by Django 5.2.7 on 2025-10-31 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AssistantTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='chat.assistant')),
            ],
        ),
    ]
