# Generated by Django 5.2.7 on 2025-12-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_sent_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_group',
        ),
    ]
