# Generated by Django 5.2.7 on 2025-10-31 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_assistant_description_assistanttags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistanttags',
            old_name='tag',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='assistanttags',
            name='assistant',
        ),
        migrations.AddField(
            model_name='assistant',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='chat.assistanttags'),
            preserve_default=False,
        ),
    ]
