# Generated by Django 5.2.7 on 2025-12-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_conversation_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationusers',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
