# Generated by Django 5.2.7 on 2025-10-31 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_tag_assistanttags_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='chat.assistanttags'),
        ),
    ]
