# Generated by Django 5.2.7 on 2025-12-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversationusers_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
