# Generated by Django 5.2.7 on 2025-10-31 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_assistant_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat.assistant')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='chat.conversation')),
            ],
        ),
    ]
