# Generated by Django 5.2.7 on 2025-11-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversationassistant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='conversationassistant',
            name='assistant',
        ),
        migrations.RemoveField(
            model_name='conversationassistant',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='AssistantTags',
        ),
        migrations.DeleteModel(
            name='Assistant',
        ),
        migrations.DeleteModel(
            name='ConversationAssistant',
        ),
    ]
