# Generated by Django 5.2.6 on 2025-09-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
