# Generated by Django 5.2.7 on 2025-11-09 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_log_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=50, unique=True)),
                ('daily_limit', models.PositiveIntegerField(help_text='Max tokens per day for this plan')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='token_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tokenplan'),
        ),
        migrations.CreateModel(
            name='UserTokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('used_tokens', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='accounts.user')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
